import Navbar from '@/views/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/views/Footer/Footer'
import Providers from '@/components/utils/Providers'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home - Dine Market',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className='text-pri_black'>
     
      <body className={`${inter.className} w-full `}>
        <Toaster/>
      <ClerkProvider>
      <Providers>
      <Navbar/>
        {children}
        <Footer/>
      </Providers>
      </ClerkProvider>
        </body>
    </html>
  )
}
